DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS fastlaps CASCADE;
DROP TABLE IF EXISTS podiums CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS series CASCADE;


CREATE TABLE series (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE teams  (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  country VARCHAR(255)
);

CREATE TABLE vehicles(
  id SERIAL PRIMARY KEY NOT NULL,
  car VARCHAR(255) NOT NULL,
  number VARCHAR(6),
  classification VARCHAR(255),
  team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  series_id INTEGER REFERENCES series(id) ON DELETE CASCADE
);

CREATE TABLE drivers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  rating VARCHAR(255),
  nationality VARCHAR(255),
  team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE CASCADE
);

CREATE TABLE podiums (
  id SERIAL PRIMARY KEY NOT NULL,
  class VARCHAR(255) NOT NULL,
  first_place INTEGER REFERENCES drivers(id),
  second_place INTEGER REFERENCES drivers(id),
  third_place INTEGER REFERENCES drivesr(id)
);

CREATE TABLE fastlaps (
  id SERIAL PRIMARY KEY NOT NULL,
  driver_id INTEGER REFERENCES drivers(id) NOT NULL,
  laptime VARCHAR(255) NOT NULL
);

CREATE TABLE results (
  id SERIAL PRIMARY KEY NOT NULL,
  event INTEGER REFERENCES events(id) NOT NULL,
  series_id INTEGER REFERENCES series(id) ON DELETE CASCADE
  podium1 INTEGER REFERENCES podiums(id),
  podium2 INTEGER REFERENCES podiums(id),
  podium3 INTEGER REFERENCES podiums(id),
  fastlap_id INTEGER REFERENCES fastlaps(id)
);