DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;

CREATE TABLE teams  (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
);

CREATE TABLE vehicles(
  id SERIAL PRIMARY KEY NOT NULL,
  manufacturer VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  number VARCHAR(6),
  classification VARCHAR(255),
  team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE
)

CREATE TABLE drivers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  rating VARCHAR(255),
  team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  vehicle_id INTEGER REFERENCES vehicle(id) ON DELETE CASCADE
);