const vehicles = {
    gtwca: [
        "Acura NSX GT3 EVO22",
        "Aston Martin Vantage AMR GT3",
        "Audi R8 LMS GT2",
        "Audi R8 LMS GT3 EVO II",
        "BMW M4 GT3",
        "Bentley Continental GT3",
        "Chevrolet Corvette Z06 GT3.R",
        "Corvette C7 GT3-R",
        "Ferrari 296 GT3",
        "Ferrari 488 GT3",
        "Ford Mustang GT3",
        "KTM X-Bow GT2",
        "Lamborghini Huracan GT3 EVO2",
        "Lexus RC F GT3",
        "Maserati MC20 GT2",
        "McLaren 720S GT3 EVO",
        "Mercedes-AMG GT3",
        "Nissan GT-R GT3 2018",
        "Porsche 911 GT2 RS Clubsport",
        "Porsche 911 GT3 R (991)",
        "Porsche 911 GT3 R (991.ii)",
        "Porsche 911 GT3 R (992)",
    ],
};
