const vehicles = {
    gtwca: [
        "Acura NSX GT3 EVO22",
        "Aston Martin Vantage AMR GT3",
        "Audi R8 LMS GT2",
        "Audi R8 LMS GT3 EVO II",
        "BMW M4 GT3",
        "Bentley Continental GT3",
        "Chevrolet Corvette Z06 GT3.R",
        "Corvette C7 GT3-R",
        "Ferrari 296 GT3",
        "Ferrari 488 GT3",
        "Ford Mustang GT3",
        "KTM X-Bow GT2",
        "Lamborghini Huracan GT3 EVO2",
        "Lexus RC F GT3",
        "Maserati MC20 GT2",
        "McLaren 720S GT3 EVO",
        "Mercedes-AMG GT3",
        "Nissan GT-R GT3",
        "Porsche 911 GT2 RS Clubsport",
        "Porsche 911 GT3 R (991)",
        "Porsche 911 GT3 R (991.ii)",
        "Porsche 992 GT3 R",
    ],
    pgt4a: [
        "Alpine A110 GT4",
        "Aston Martin Vantage AMR GT4",
        "Audi R8 LMS GT4",
        "BMW M4 GT4",
        "BMW M4 GT4 (G82)",
        "Ford Mustang GT4",
        "Ginetta G56 GT4",
        "Lotus Emira GT4",
        "McLaren Artura GT4",
        "Mercedes-AMG GT4",
        "Nissan Z GT4",
        "Porsche 718 Cayman GT4 Clubsport MR",
        "Porsche 718 Cayman GT4 RS Clubsport",
        "Saleen S1",
        "Toyota Gazoo Racing GR Supra GT4 EVO",
    ],
    gta: [
        "Acura NSX GT3 EVO22",
        "Alpine A110 GT4",
        "Aston Martin Vantage AMR GT3",
        "Aston Martin V12 Vantage GT3",
        "Aston Martin Vantage AMR GT3 2024",
        "Aston Martin Vantage AMR GT4",
        "Audi R8 LMS",
        "Audi R8 LMS GT2",
        "Audi R8 LMS GT4",
        "Bentley Continental GT3 2018",
        "BMW E89 Z4",
        "BMW F13 M6 GT3",
        "BMW M4 GT3",
        "BMW M4 GT4",
        "BMW M4 GT4 (G82)",
        "Callaway Corvette Z06R GT3",
        "Chevrolet Corvette Z06 GT3.R",
        "Corvette C7 GT3-R",
        "Ferrari 296 GT3",
        "Ferrari 488 GT3",
        "Ferrari 488 Italia GT3",
        "Ford Mustang GT3",
        "Ford Mustang GT4",
        "Ginetta G56 GT4",
        "KTM X-Bow GT2",
        "Lamborghini Huracan GT3",
        "Lamborghini Huracan GT3 EVO2",
        "Lamborghini Huracan Super Trofeo EVO",
        "Lamborghini Huracan Super Trofeo EVO2",
        "Lamborghini-D Gallardo LP 560-4",
        "Lexus RC F GT3",
        "Lotus Emira GT4",
        "Maserati MC20 GT2",
        "McLaren 720S GT3 EVO",
        "McLaren Artura GT4",
        "McLaren MP4-12C",
        "Mercedes-AMG GT3",
        "Mercedes-AMG GT4",
        "Mercedes-Benz SLS AMG GT3",
        "Nissan GT-R GT3 2018",
        "Nissan GT-R Nismo GT3",
        "Nissan Z GT4",
        "Porsche 718 Cayman GT4 Clubsport MR",
        "Porsche 718 Cayman GT4 RS Clubsport",
        "Porsche 911 GT2 RS Clubsport",
        "Porsche 911 GT3 R",
        "Porsche 911 GT3 R (991)",
        "Porsche 911 GT3 R (991.ii)",
        "Porsche 992 GT3 R",
        "Saleen S1",
        "Toyota Gazoo Racing GR Supra GT4 EVO",
    ],
};

export default vehicles;
